Update CltTasksUtility.ps1
microsoft/azure-pipelines-tasks pull request #14715
Opened 2021-04-12 11:43 UTC by anshii03

We want the CLT tasks to fail gracefully with proper error message indicating that the service is now shutdown.

**Task name**:  Cloud Load Test Task

**Description**: Catching proper error message and displaying so that customer knows that service is now shutdown.

**Documentation changes required:** N

**Added unit tests:** (Y/N)  N

**Attached related issue:** (Y/N) [https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1831804]

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

2021-04-12 11:49 UTC, gnsip commented on Tasks/RunLoadTestV1/CltTasksUtility.ps1
> +	{
Nit: proper indentation needed here

2021-04-12 11:49 UTC, gnsip commented on Tasks/RunLoadTestV1/CltTasksUtility.ps1
> +	{
Nit: proper indentation needed here

2021-04-12 12:02 UTC, gnsip commented on Tasks/RunLoadTestV1/CltTasksUtility.ps1
> +        throw "Error"
Can you please be more clear with this message here? 
e.g. "Error occurred while calling API: $method $uri"

2021-04-12 12:15 UTC, gnsip commented on Tasks/RunLoadTestV1/CltTasksUtility.ps1
>  }
You need to update patch version of the task, please see the earlier commits for this task or any other task

2021-04-12 12:24 UTC, ganesp requested changes
Please address the review comments.
Also validate and share screenshots for both scenarios -- shutdown enabled/disabled

2021-04-14 07:07 UTC, gnsip approved these changes

2021-04-14 07:08 UTC, gnsip approved these changes

2021-04-14 07:09 UTC, ganesp approved these changes

2021-04-14 07:50 UTC, merged