Migrate NuGetRestoreV1 task to Node10
microsoft/azure-pipelines-tasks pull request #15855
Opened 2022-02-01 12:14 UTC by golubev-ivan

**Task name**: NuGetRestoreV1

**Description**: Migrated NuGetRestoreV1 task to Node10.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped
- [ ] Checked that applied changes work as expected

2022-02-02 07:55 UTC, DaniilShmelev approved these changes

2022-02-02 09:03 UTC, anatolybolshakov commented
@golubev-ivan could you please describe shortly which scenarios have you tested?

2022-02-02 09:04 UTC, anatolybolshakov approved these changes

2022-02-02 10:17 UTC, EzzhevNikita approved these changes

2022-02-02 10:54 UTC, golubev-ivan commented
> @golubev-ivan could you please describe shortly which scenarios have you tested?

I manually tested this task using a simple project without external packages.

2022-02-02 10:54 UTC, golubev-ivan commented
cc @geekzter for visibility

2022-03-02 19:39 UTC, golubev-ivan commented
Hi @aasim, @phil-hodgson, Could you please take a look at this PR?

2022-06-30 13:40 UTC, DmitriiBobreshev commented
/azp run

2022-06-30 15:48 UTC, DmitriiBobreshev commented
Test results are [here](https://github.com/microsoft/build-task-team/issues/3190)

2022-07-06 07:52 UTC, DmitriiBobreshev commented
Hi @phil-hodgson, @aasim, @satba Could you please take a look at this PR?

2022-07-25 17:30 UTC, tintse-thxsky-MSFT requested changes
please look at the comment in package json

2022-07-26 12:26 UTC, mpodriezov commented on Tasks/NuGetRestoreV1/package.json
> -    "packaging-common": "file:../../_build/Tasks/Common/packaging-common-1.0.1.tgz",
why do you think so @tintse-thxsky-MSFT ? We moved that as separate repos to not use file:/../../ aproach.

2022-07-27 18:21 UTC, tintse-thxsky-MSFT commented on Tasks/NuGetRestoreV1/package.json
> -    "packaging-common": "file:../../_build/Tasks/Common/packaging-common-1.0.1.tgz",
Never mind.  This is good.

2022-07-27 18:21 UTC, tintse-thxsky-MSFT approved these changes

2022-07-28 10:06 UTC, mpodriezov commented
/azp run

2022-07-28 17:19 UTC, tintse-thxsky-MSFT approved these changes

2022-07-28 18:44 UTC, tintse-thxsky-MSFT commented
/azp run

2022-07-28 18:59 UTC, tintse-thxsky-MSFT commented
/azp run

2022-08-01 11:17 UTC, mpodriezov commented
/azp run

2022-08-02 17:37 UTC, merged