Migrate download GitHub nuget package v1 to node10
microsoft/azure-pipelines-tasks pull request #16027
Opened 2022-03-15 10:30 UTC by denis-tikhomirov

**Task name**: DownloadGithubNugetPackageV1

**Description**: this pull request provides updating the NpmAuthenticateV0 task and its migration to Node 10

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

2022-03-15 11:05 UTC, denis-tikhomirov commented
Changes in the PR are prepared to migrate task DownloadGithubNugetPackageV1 to Node10.
@richakumar, @harshiniks, could you please help with testing of the changes? I see in code owners list that you are owners of DownloadGithubNugetPackageV1 task.

2022-03-15 14:13 UTC, denis-tikhomirov commented
@mmrazik, please take a look at the PR.

2022-03-15 14:14 UTC, EzzhevNikita approved these changes

2022-05-09 13:58 UTC, mmrazik requested changes

2022-05-09 13:58 UTC, mmrazik commented on Tasks/DownloadGitHubNugetPackageV1/task.json
> +        "Minor": 202,
Can we bump the version here, please?

2022-05-09 13:59 UTC, mmrazik commented on Tasks/DownloadGitHubNugetPackageV1/task.json
> +        "Minor": 202,
Please ping me via Teams once updated.

2022-05-12 12:03 UTC, KonstantinTyukalov commented
/azp run

2022-06-02 16:40 UTC, max-zaytsev commented on Tasks/DownloadGitHubNugetPackageV1/task.json
> +        "Minor": 202,
Updated to 206

2022-06-03 12:23 UTC, mmrazik approved these changes

2022-06-03 12:28 UTC, v-nmursapall approved these changes
Looks good. Approved

2022-06-04 15:57 UTC, merged