{AzurePipelineTasks} fixes Azure/azure-powershell#19209
microsoft/azure-pipelines-tasks pull request #16785
Opened 2022-08-23 05:03 UTC by navba-MSFT

fixes Azure/azure-powershell#19209

Customers have reported an issue with the Pipeline tasks for while it tries to fetch the storage account details it fails with below error:

##[error]Storage account: <my existing and accessible storage account> not found. The selected service connection 'Service Principal' supports storage accounts of Azure Resource Manager type only.

Cause of the issue:
Get-AzureRmStorageAccount is outdated and needs to be replaced with Get-AzStorageAccount.

**Task name**: <Name of changed or new pipeline task>

**Description**: <Describe your changes here>

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

2022-08-29 06:39 UTC, mmrazik commented
Please bump the task version (see the checklist in the PR description). Try to rebase also on latest master.

2022-08-29 06:41 UTC, mmrazik commented
Or maybe wait. This will probably need some more work. Is there any specific reason why you are fixing this in V4 of the task?

2022-08-29 06:46 UTC, navba-MSFT commented
> Or maybe wait. This will probably need some more work. Is there any specific reason why you are fixing this in V4 of the task?

@mmrazik I just tried to change everywhere the `Get-AzureRmStorageAccount `was referenced, Since that the old PS module and should be changed to Get-AzStorageAccount. So I changed it in both v4 and v5 tasks.

2022-08-29 13:48 UTC, mmrazik requested changes
Please bump the version of the task you are changing.

2022-08-29 13:49 UTC, mmrazik commented
/azp run

2022-08-29 13:49 UTC, mmrazik commented
/azp run

2022-08-30 14:31 UTC, v-nagarajku commented
I have completed this PR - https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps/pullrequest/663407
for creating AzureFileCopyV5 task.
cc: @mmrazik @PhilipsonJoseph

2022-08-31 12:12 UTC, navba-MSFT commented
@v-nagarajku Thanks for reviewing this PR. I see all the checks have been passed. May I know when this PR would be merged  / released ?

2022-09-01 13:18 UTC, PhilipsonJoseph commented
/azp run

2022-09-02 02:45 UTC, navba-MSFT commented
@mmrazik @PhilipsonJoseph @v-nagarajku Since all the checks have been passed. May I know when this PR would be merged / released ?

2022-09-02 05:32 UTC, PhilipsonJoseph commented
@mmrazik  Yes this changes are applicable for v4 too as there is an issue on fetching storage accounts. 

@navba-MSFT Yes you are good to merge the PR. Before that please resolve the Martin's comment

2022-09-02 05:36 UTC, navba-MSFT commented
@PhilipsonJoseph 

> Please bump the version of the task you are changing.

This has been done. Also I am not authorized to merge this PR. Could you please help to merge this PR ?

2022-09-02 12:52 UTC, mmrazik approved these changes

2022-09-02 14:26 UTC, mmrazik commented
/azp run

2022-09-02 14:43 UTC, merged

2022-09-29 07:51 UTC, nijoshms commented on Tasks/AzureFileCopyV4/task.json
> +        "Minor": 210,
This PR caused issue; we will revert the task.