Add `deprecationMessage` for deprecated `DownloadPackageV0` and `NuGet...` tasks
microsoft/azure-pipelines-tasks pull request #19457
Opened 2024-01-23 11:30 UTC by DenisRumyantsev

***Tasks:***
DownloadPackage@0
NuGetAuthenticate@0
NuGetInstaller@0
NuGetPackager@0
NuGetPublisher@0
NuGetRestore@1
NuGet@0

***Description:*** Add the tailored deprecation message in addition to the common deprecation message.

***Documentation changes required:*** No

***Added unit tests:*** No

***Attached related issue:*** N/A

***Checklist:***
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

2024-02-23 13:55 UTC, amp-powell approved these changes
I'm approving, but possibly we can add links when suggesting the new tasks to use. Also, it's fine to add the depreciationMessage property to DownloadPackageV0, NuGetInstallerV0, and NuGetRestoreV1, but these tasks are already failing.

2024-02-27 08:13 UTC, DenisRumyantsev commented
@amp-powell This PR has been created in addition to [another one](https://github.com/microsoft/azure-pipelines-tasks/pull/19443). The link to the documentation is not provided in the tailored deprecation message since it is already included in the common deprecation message.

2024-02-27 09:02 UTC, geekzter requested changes

2024-02-27 09:02 UTC, geekzter commented on Tasks/DownloadPackageV0/task.json
This task has already been disabled in Azure DevOps Service, we can still update it though

2024-02-27 09:02 UTC, geekzter commented on Tasks/NuGetInstallerV0/task.json
This task has already been disabled in Azure DevOps Service, we can still update it though

2024-02-27 09:02 UTC, geekzter commented on Tasks/NuGetInstallerV0/task.loc.json
This task has already been disabled in Azure DevOps Service, we can still update it though

2024-03-04 13:43 UTC, DmitriiBobreshev commented
/azp run

2024-03-06 06:55 UTC, geekzter approved these changes

2024-03-06 10:25 UTC, merged