Bump the task-lib version for script tasks
microsoft/azure-pipelines-tasks pull request #19656
Opened 2024-03-19 13:05 UTC by DenisNikulin5

**Task name**: AzureCLIV1, AzureCLIV2, AzurePowerShellV2, AzurePowerShellV3, AzurePowerShellV4, AzurePowerShellV5, BashV3, CmdLineV2, PowerShellOnTargetMachinesV2, PowerShellOnTargetMachinesV3, PowerShellV2, PythonScriptV0, ShellScriptV2, SshV0

**Description**: Updated the task-lib version to apply changes from https://github.com/microsoft/azure-pipelines-task-lib/pull/1027

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

2024-03-19 13:32 UTC, DergachevE approved these changes

2024-03-19 13:54 UTC, vmapetr approved these changes

2024-03-19 13:59 UTC, kirill-ivlev approved these changes

2024-03-19 14:31 UTC, max-zaytsev requested changes

2024-03-19 14:31 UTC, max-zaytsev commented on _generated/AzurePowerShellV4.versionmap.txt
> +Default|4.237.3
This looks incorrect 
Do we already have AzurePowerShellV4@4.237.3?

2024-03-20 08:17 UTC, max-zaytsev approved these changes

2024-03-20 09:34 UTC, merged