Added AzureRmWebAppDeploymentV5 to support OneDeploy for Linux App Service
microsoft/azure-pipelines-tasks pull request #20703
Opened 2024-11-29 11:55 UTC by ShilpiRachna1

**Task name**: AzureRmWebAppDeployment

**Description**: 
1. Added AzureRmWebAppDeploymentV5 to support OneDeploy for Linux App Service.
2. OneDeploy supports both clean (default) and incremental deployment options. For incremental deployment option, user needs to specify AdditionalArguments parameter with '-clean:false'
3. We can fallback to ZipDeploy by specifying DeploymentType parameter as zipDeploy.
4. Both onedeploy and zipDeploy for LinuxAppService use the newer common package to compute checksum for the attached zip or jar file.

**Documentation changes required:** Y

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

2024-12-04 08:02 UTC, ShilpiRachna1 commented
This PR depends on https://github.com/microsoft/azure-pipelines-tasks-common-packages/pull/411 and should be merged only after that PR is merged.

2024-12-17 12:42 UTC, z00sts reviewed
![image](https://github.com/user-attachments/assets/d21d82d7-9baa-411e-8938-7e61e24eb9db)
Is it possible to split this PR into few?

Also, can you fix those lines in the description?
![image](https://github.com/user-attachments/assets/8044b77b-2649-4948-9d86-e1e3ef484cde)

2024-12-19 07:23 UTC, v-schhabra requested changes
Hi @ShilpiRachna1 
When we are selecting webapp of type Linux then actually in the UI of release pipeline we do not have "Additional argument" text box.
So, it would not be possible to give any arguments here or to select one deploy incremental deployment option.

2024-12-19 07:25 UTC, v-schhabra commented on Tasks/AzureRmWebAppDeploymentV5/_buildConfigs/Node20/package.json
> +    "azure-pipelines-tasks-azure-arm-rest": "^3.246.4",
Hi @ShilpiRachna1 
Please update here the package version of "azure-pipelines-tasks-azure-arm-rest".

2024-12-22 19:32 UTC, ShilpiRachna1 commented
> Hi @ShilpiRachna1 When we are selecting webapp of type Linux then actually in the UI of release pipeline we do not have "Additional argument" text box. So, it would not be possible to give any arguments here or to select one deploy incremental deployment option.

Fixed the UI. Please test again

2024-12-22 19:34 UTC, ShilpiRachna1 commented
> ![image](https://private-user-images.githubusercontent.com/5012880/396500836-d21d82d7-9baa-411e-8938-7e61e24eb9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4OTYyMTUsIm5iZiI6MTczNDg5NTkxNSwicGF0aCI6Ii81MDEyODgwLzM5NjUwMDgzNi1kMjFkODJkNy05YmFhLTQxMWUtODkzOC03ZTYxZTI0ZWI5ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTkzMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJiMWY4MDJhNzBiMTAzODJkNTRlNDRlYTdkMTIwMjI4MDk3NDAxNTk1NTNiODY2OTAyOWNmYjNlMTNkNDYxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hyQ2u3EnpfHTUZmO_bFFTZugZBh7oM7bWsrWLB4L0o0) Is it possible to split this PR into few?
> 
> Also, can you fix those lines in the description? ![image](https://private-user-images.githubusercontent.com/5012880/396501188-8044b77b-2649-4948-9d86-e1e3ef484cde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4OTYyMTUsIm5iZiI6MTczNDg5NTkxNSwicGF0aCI6Ii81MDEyODgwLzM5NjUwMTE4OC04MDQ0Yjc3Yi0yNjQ5LTQ5NDgtOWQ4Ni1lMWUzZWY0ODRjZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTkzMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODdhYTc1OTQxMzI0OWY2NzZkYjBkMThmMDhhNWMyMDg4NzU4ZWNhMGU0NjEwNmYwOTU3OWEwZWQ1M2E1ZjU3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.prWQTE-h3GHLQt-Zky5_JfW4oXXj2CulrRVK69gRFM4)

@z00sts - Since this is a new major version of the task, I am not sure if I can split the PR. If it helps, I have created another PR copying the newer changes to older version of the same task - that ould help understand what is actually changing.

https://github.com/microsoft/azure-pipelines-tasks/pull/20736/files

2024-12-27 10:15 UTC, ShilpiRachna1 commented
> Hi @ShilpiRachna1 When we are selecting webapp of type Linux then actually in the UI of release pipeline we do not have "Additional argument" text box. So, it would not be possible to give any arguments here or to select one deploy incremental deployment option.

@v-schhabra - This has been fixed. Now you would see the Additional Deployment options with deployment type dropdown and clean deployment checkbox

2025-01-06 05:21 UTC, v-schhabra submitted a review, later dismissed
LGTM

2025-01-06 09:01 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/_buildConfigs/Node20/package.json
> +    "azure-pipelines-tasks-azure-arm-rest": "^3.246.4",
Done

2025-01-07 10:45 UTC, z00sts commented
![image](https://github.com/user-attachments/assets/1f772f36-dbc7-4a04-a27c-52b56b4a7601)
Let's create a work item to address codeowners file issues

2025-01-07 12:32 UTC, z00sts commented
Do we have a work item for this? Can you link it here?

2025-01-08 15:47 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
> +                        { slotName: this.appService.getSlot() }, 'Zip', true);
This `if (zipDeploy)` statement is copypasted almost identical 3 times in this file - looks like it will be better to extract separate function for it

2025-01-08 15:47 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
> +                        { slotName: this.appService.getSlot() }, 'Zip', true);
It is visible here: https://github.com/microsoft/azure-pipelines-tasks/pull/20736/files#diff-7bb6d6cb11c0624930d8ce1099ad11c7bdd554b0901c19a7bcc923d77207d6be

2025-01-08 15:54 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                await webClient.sleepFor(5);
sleep(5)? Maybe we need to do polling with timeout here to add stability?

2025-01-08 16:04 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                packageType = 'Zip'
Why not `PackageType.zip`?

2025-01-08 16:13 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                tl.debug('Wait for 5 seconds for app_offline to take effect');
For me it's not clear what we are doing here. If app is offline we are calling some hook called appOfflineKuduService and waiting for 5 seconds to "take effect". What we are waiting for here? Maybe we should rename _appOfflineKuduService method.

2025-01-08 16:13 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                packageType = 'Zip'
IMO we need debug log line here - "no packageType: fallback to zip package type"

2025-01-08 16:16 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +            console.log("NOTE: Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.");
This log line goes without localization. Is it by intention?

2025-01-08 16:28 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/task.json
> +        "oneDeploy": "One Deploy",
Since "one deploy" is not some well-known default deployment strategy for Linux machines (usually it's tar/zip) - should we add link to one deploy official docs here?

2025-01-09 11:04 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +            console.log("NOTE: Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.");
Added loc- seems to be a day zero miss

2025-01-09 11:24 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
> +                        { slotName: this.appService.getSlot() }, 'Zip', true);
Fixed

2025-01-09 11:26 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +        }
Following the same pattern as every other API. I agree with the feedback - but we should take any refactoring changes later. This is critical for customers and given it is a completely new codebase for us, I want to take a very targeted fix now.

2025-01-09 11:27 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/task.json
> +        "oneDeploy": "One Deploy",
Reaching out to the doc team as advised. Will change things accordingly

2025-01-09 11:28 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                packageType = 'Zip'
Changed

2025-01-09 11:33 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                await webClient.sleepFor(5);
Following the same pattern as every other API for now. Taking the targeted fix now.

2025-01-09 11:37 UTC, ShilpiRachna1 commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                tl.debug('Wait for 5 seconds for app_offline to take effect');
Waiting to enable app offline mode. I don't have much context here. So, keeping it unchanged

2025-01-09 13:09 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/task.json
> +        "oneDeploy": "One Deploy",
Thanks

2025-01-09 13:11 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                await webClient.sleepFor(5);
I've created a WI for removing sleeps: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2241786

2025-01-09 13:11 UTC, z00sts commented on Tasks/AzureRmWebAppDeploymentV5/operations/KuduServiceUtility.ts
> +                tl.debug('Wait for 5 seconds for app_offline to take effect');
Should be fixed here: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2241786

2025-01-09 13:12 UTC, z00sts approved these changes

2025-01-16 06:28 UTC, v-gayatrij commented
/azp run

2026-07-19 00:49 UTC, closed without merging